### ISSUE TITLE
Debugging works only the first time with release 1.5.2

### ISSUE THREAD

**Issue by Lucky-Mic** [decacis/godot_oculus_platform#11]
### Godot Oculus Platform version

Godot Oculus Platform v1.5.2 for Godot 4.2.0+ with SDK v68.0

### Meta Quest OS version

v69

### Issue description

In my program I use initialize_android in the _ready function and have a active breakpoint before the initialize_android call. 
I can start my program with v1.5.1 with the debugger without any problems but if I use the same program with v1.5.2, the program works only once. First start,the initialize returns true and the game continues. After closing and restarting the game, the game freezes at startup and doesn't stop in the _ready function. It seems a process is freezed (it's not adb.exe!) and only a windows restart will help. Changing back to v1.5.1 and the problem is gone.

### Steps to reproduce

Use a test program with initialize_android in the _ready function and activate a breakpoint before the initialize_android call. Start the program with active debugger twice and the program will be freezed after second start. Try the same test with v1.5.1 and you will not have the problem.

**Comment by Lucky-Mic** [comment]
Seems to be a problem with Godot 4.3 (stable) and not the new release

**Comment by decacis** [comment]
Hi, thank you for the report! How did you figure out that the problem is with Godot 4.3 and not this add-on v1.5.2?

I ask because this could still be an issue with the add-on (though unlikely). For example, if it works every time using v1.5.1 with Godot 4.3 but not when using v1.5.2 with Godot 4.3.

**Comment by Lucky-Mic** [comment]
Hi...

I confused my self with v1.5.1 and using "Keep Debug Server Open", which allows the debugging until I close Godot and reopen it. Without this option, I can only debug my program one time, with 1.5.1 and also with 1.5.2.
I also removed (for testing) the addon from my project, used the default settings for debugging and I've the same problem, so I think it's a strange problem with Godot 4.3 and not with your addon.
I don't find the reason of this problem until now. I only know it's freezed in the Quest until I kill the adb.exe process, then the program continues on Quest side.

Thanks you for your great addon, it's a big advantage to Godot!

Kind regards,
Mic

________________________________
Von: Daniel Castellanos ***@***.***>
Gesendet: Dienstag, 8. Oktober 2024 21:25
An: decacis/godot_oculus_platform ***@***.***>
Cc: Mic ***@***.***>; State change ***@***.***>
Betreff: Re: [decacis/godot_oculus_platform] Debugging works only the first time with release 1.5.2 (Issue #11)


Hi, thank you for the report! How did you figure out that the problem is with Godot 4.3 and not this add-on v1.5.2?

I ask because this could still be an issue with the add-on (though unlikely). For example, if it works every time using v1.5.1 with Godot 4.3 but not when using v1.5.2 with Godot 4.3.
