### ISSUE TITLE
Incorrect example classes

### ISSUE THREAD

**Issue by Blockyheadman** [decacis/godot_oculus_platform#2]
### Documentation URL

https://decacis.github.io/godot_oculus_platform/functions/achievements/#achievements_get_all_progress

### Error description

In the example of how it can be used, there are 2 types and a function that don't exist on the current release (1.2.0-beta). `GDOPAchievementProgArray` && `GDOP.array_get_all(achievements_prog` don't exist.

**Comment by decacis** [comment]
Thank you for reporting! I updated the example just now.
