### ISSUE TITLE
Will there be a release for Godot 4.2?

### ISSUE THREAD

**Issue by ikonnow** [decacis/godot_oculus_platform#4]
### Feature description

I am wondering if there will be a godot 4.2 version of the plugin, since I am interested in using the latest features of the engine. Thank you for your work and your support.

**Comment by decacis** [comment]
Hi, yes! I was a bit busy the past week but I'll try to update it either this weekend or next week.

**Comment by ikonnow** [comment]
> Hi, yes! I was a bit busy the past week but I'll try to update it either this weekend or next week.

Nice, that's great to hear!

**Comment by decacis** [comment]
Hey, I just updated the plugin to Godot 4.2, you can download it here: https://github.com/decacis/godot_oculus_platform/releases/tag/v1.4.0-beta_godot-4.2.0-stable_sdk-59.0
